apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubinot-data
  namespace: network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rubinot-data
  template:
    metadata:
      labels:
        app: rubinot-data
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: harbor.cddlabs.casa/giovannirco/rubinot-data:latest
          imagePullPolicy: Always
          env:
            - name: RUBINOT_BASE_URL
              value: https://www.rubinot.com.br
            - name: GIN_MODE
              value: release
            - name: APP_VERSION
              value: v0.1.0
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: rubinot-data
  namespace: network
spec:
  selector:
    app: rubinot-data
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rubinot-api-route
  namespace: network
spec:
  hostnames:
    - api.rubinot.dev
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: rubinot-data
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rubinot-api-internal-route
  namespace: network
spec:
  hostnames:
    - api.rubinot.dev
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: rubinot-data
          port: 80
